## Place your custom repositories here, they must match the architecture and version.
# src/gz %n %U
# src custom file:///usr/src/openwrt/bin/%T/packages

src/gz immortalwrt_core https://downloads.immortalwrt.org/releases/18.06-k5.4-SNAPSHOT/targets/x86/64/packages
src/gz immortalwrt_base https://downloads.immortalwrt.org/releases/18.06-k5.4-SNAPSHOT/packages/x86_64/base
src/gz immortalwrt_kmods https://downloads.immortalwrt.org/releases/18.06-k5.4-SNAPSHOT/targets/x86/64/kmods/5.4.203-1-8fb8a7f384afdf9177e1280624d47cde
src/gz immortalwrt_luci https://downloads.immortalwrt.org/releases/18.06-k5.4-SNAPSHOT/packages/x86_64/luci
src/gz immortalwrt_packages https://downloads.immortalwrt.org/releases/18.06-k5.4-SNAPSHOT/packages/x86_64/packages
src/gz immortalwrt_routing https://downloads.immortalwrt.org/releases/18.06-k5.4-SNAPSHOT/packages/x86_64/routing
src/gz immortalwrt_telephony https://downloads.immortalwrt.org/releases/18.06-k5.4-SNAPSHOT/packages/x86_64/telephony

## This is the local package repository, do not remove!
src imagebuilder file:packages

option check_signature